# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps: 
    
    - uses: actions/checkout@v3
    - name: Access GitHub Variables
      run: |
         echo "GitHub Token: ${{ secrets.GITHUB_TOKEN }}"
         echo "Custom Secret: ${{ secrets.CUSTOM_SECRET }}"
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip       
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi   
        
    - name:  Run forwarder
      env:
        TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
        TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}      
        CHANNEL_USERNAME: ${{ envs.CHANNEL_USERNAME }} 
      run: python main.py
      
